config/routes.rb
Mesinvites::Application.routes.draw do
  resources :meals
  resources :guests
  resources :search, :only => [:index]

  get "meals/index"

  match 'search/:query' => 'search#search', :as => :search

  root :to => 'meals#index'

end

app/models/guest.rb
class Guest < ActiveRecord::Base
	attr_accessible :name

	has_many :meal
end

app/models/meal.rb
class Meal < ActiveRecord::Base
	attr_accessible :meal_date, :diner, :aperitif, :starter, :course, :cheese, :salad, :dessert, :notes
	
	belongs_to :guest

	def self.search(query)
		Meal.joins(:guest).where('guests.name' => query).order("meal_date DESC")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController

	def index
		@guests = Guest.all

		respond_to do |format|
			format.json { render :json => @guests }
		end
	end

end	

app/controllers/meals_controller.rb
# encoding: UTF-8

class MealsController < ApplicationController
  # GET /meals
  # GET /meals.json
  def index
    @meals = Meal.order("meal_date DESC").all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @meals }
    end
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
    @meal = Meal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @meal }
    end
  end

  # GET /meals/new
  # GET /meals/new.json
  def new
    @meal = Meal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @meal }
    end
  end

  # GET /meals/1/edit
  def edit
    @meal = Meal.find(params[:id])
  end

  # POST /meals
  # POST /meals.json
  def create
    @guest_name = params[:meal][:guest_name]
    params[:meal].delete :guest_name
    @guest = Guest.where(:name => @guest_name).first
    if (@guest.nil?)
      @guest = Guest.new
      @guest.name = @guest_name
    end

    @meal = Meal.new(params[:meal])
    @meal.guest = @guest

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, :notice => 'Le repas a été créé avec succès.' }
        format.json { render :json => @meal, :status => :created, :location => @meal }
      else
        format.html { render :action => "new" }
        format.json { render :json => @meal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /meals/1
  # PUT /meals/1.json
  def update
    @meal = Meal.find(params[:id])

    respond_to do |format|
      @guest_name = params[:meal][:guest_name]
      params[:meal].delete :guest_name
      @guest = Guest.where(:name => @guest_name).first
      if (@guest.nil?)
        @guest = Guest.new
        @guest.name = @guest_name
      end
      @meal.guest = @guest      
      if @meal.update_attributes(params[:meal])
        format.html { redirect_to @meal, :notice => 'Le repas a été mis à jour avec succès.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @meal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy

    respond_to do |format|
      format.html { redirect_to meals_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	
	def search
		@meals = Meal.search(params['query'])
		respond_to do |format|
	      format.html
	      format.json { render :json => @meals }
	    end
  	end

  	def index
  		redirect_to :action => "search", :query => params['query']
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mes Invités" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="brand" href="/">Mes Invités</a>
          
          <%= form_tag({:controller => 'search'}, :method => 'get', :class => 'navbar-form form-search pull-right') do %>
            <div class="input-append">
              <%= text_field_tag :query, params[:query], :class => "span2 search-query", :placeholder => "Recherche", :databehaviour => 'invites-autocomplete' %>
              <button type="submit" class="btn"><i class="icon-search"></i></button>
            </div>
          <% end %>

        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span10 offset1">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
    </div>
    
    <footer class="footer">
      <p>&copy; 2013 Florian MARIN</p>
    </footer>


    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/meals/_form.html.erb
<%= form_for @meal, :html => { :class => 'form-horizontal' } do |f| %>

  <div class="control-group">
    <%= f.label 'Date du repas', :class => 'control-label', :for => 'meal_date'%>
    <div class="controls">
      <div class="input-append">
        <%= f.text_field :meal_date, :value => (l(@meal.meal_date, :format => ("%d/%m/%Y")) if @meal.meal_date), :databehaviour => 'datepicker', :id => 'meal_date', :class => 'input-small' %>
        <%= f.hidden_field :diner, :id => "dinerHiddenValue" %>
        <div class="btn-group" data-toggle="buttons-radio">
          <button type="button" id="lunchButton" class="btn <%= 'active' if @meal.diner != nil && !@meal.diner %>" onClick="document.getElementById('dinerHiddenValue').value=0">Déjeuner</button>
          <button type="button" id="dinerButton" class="btn <%= 'active' if @meal.diner != nil && @meal.diner %>" onClick="document.getElementById('dinerHiddenValue').value=1">Diner</button>
        </div>
      </div>
    </div>
  </div>

  <div class="control-group">
    <%= f.label 'Invités', :class => 'control-label', :for => 'invites' %>
    <div class="controls">
      <%= f.text_field :guest_name, :value => (@meal.guest.name if @meal.guest), :databehaviour => 'invites-autocomplete', :id => 'invites' %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label 'Apéritif', :class => 'control-label', :for => 'aperitif'%>
    <div class="controls">
      <%= f.text_field :aperitif, :class => 'text_field', :id => 'aperitif', :class => 'input-xxlarge' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label 'Entrée', :class => 'control-label', :for => 'starter'%>
    <div class="controls">
      <%= f.text_field :starter, :class => 'text_field', :id => 'starter', :class => 'input-xxlarge' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label 'Plat', :class => 'control-label', :for => 'course'%>
    <div class="controls">
      <%= f.text_field :course, :class => 'text_field', :id => 'course', :class => 'input-xxlarge' %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <label class="checkbox">
        <%= f.check_box :cheese %>Fromage
      </label>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <label class="checkbox">
        <%= f.check_box :salad %>Salade
      </label>
    </div>
  </div>

  <div class="control-group">
    <%= f.label 'Dessert', :class => 'control-label', :for => 'dessert'%>
    <div class="controls">
      <%= f.text_field :dessert, :class => 'text_field', :id => 'dessert', :class => 'input-xxlarge' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label 'Notes', :class => 'control-label', :for => 'notes' %>
    <div class="controls">
      <%= f.text_area :notes, :class => 'text_area', :id => 'notes', :rows => '5', :class => 'input-xxlarge' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit "Enregistrer", :class => 'btn btn-primary' %>
    <%= link_to "Annuler",
                meals_path, :class => 'btn' %>
  </div>
<% end %>

app/views/meals/edit.html.erb
<%- model_class = Meal -%>
<div class="page-header">
  <h1>Modification d'un repas</h1>
</div>
<%= render :partial => 'form' %>

app/views/meals/index.html.erb
<%- model_class = Meal -%>
<div class="page-header">
  <h1>Mes Repas</h1>
</div>
<table class="table table-striped table-hover" id="meals_table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Invités</th>
      <th>Apéritif</th>
      <th>Entrée</th>
      <th>Plat</th>
      <th>Autre</th>
      <th>Dessert</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @meals.each do |meal| %>
      <tr>
        <td data-link="<%= meal_path(meal) %>" class="clickable"><%= l(meal.meal_date, :format => "%d/%m/%Y") if meal.meal_date %> 
          <% if meal.diner != nil %>
            <% if meal.diner %>
              Diner
            <% else %>
              Déjeuner
            <% end %>
          <% end %>
        </td>
        <td data-link="<%= meal_path(meal) %>" class="clickable"><%= meal.guest.name if meal.guest %></td>
        <td data-link="<%= meal_path(meal) %>" class="clickable"><%= meal.aperitif %></td>
        <td data-link="<%= meal_path(meal) %>" class="clickable"><%= meal.starter %></td>
        <td data-link="<%= meal_path(meal) %>" class="clickable"><%= meal.course %></td>
        <td data-link="<%= meal_path(meal) %>" class="clickable"><%= "Fromage" if meal.cheese %><%= " et " if meal.cheese && meal.salad %><%= "Salade" if meal.salad %></td>
        <td data-link="<%= meal_path(meal) %>" class="clickable"><%= meal.dessert %></td>
        <td>
          <%= link_to "Modifier",
                      edit_meal_path(meal), :class => 'btn btn-mini' %>
          <%= link_to "Supprimer",
                      meal_path(meal),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Êtes vous sûr ?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Ajouter un repas",
            new_meal_path,
            :class => 'btn btn-primary' %>

app/views/meals/new.html.erb
<%- model_class = Meal -%>
<div class="page-header">
  <h1>Ajout d'un repas</h1>
</div>
<%= render :partial => 'form' %>

app/views/meals/show.html.erb
<%- model_class = Meal -%>
<div class="page-header">
  <h1>Détail du repas</h1>
</div>

<dl class="dl-horizontal">
  
  <dt><strong>Date :</strong></dt>
  <% if @meal.meal_date %>
    <dd>
      <%= l(@meal.meal_date, :format => ("%A %d %B %Y")) %>
      <% if @meal.diner != nil %>
        <% if @meal.diner %>
          Diner
        <% else %>
          Déjeuner
        <% end %>
      <% end %>
    </dd>
  <% else %>
    <dd><em>Non précisée</em></dd>
  <% end %>
  
  <dt><strong>Invités :</strong></dt>
  <% if @meal.guest && @meal.guest.name? %>
    <dd><%= @meal.guest.name %></dd>
  <% else %>
    <dd><em>Aucun</em></dd>
  <% end %>
  
  <dt><strong>Apéritif :</strong></dt>
  <dd><%= @meal.aperitif %><em><%= "Aucun" if !@meal.aperitif? %></em></dd>
  
  <dt><strong>Entrée :</strong></dt>
  <dd><%= @meal.starter %><em><%= "Aucune" if !@meal.starter? %></em></dd>
  
  <dt><strong>Plat :</strong></dt>
  <dd><%= @meal.course %><em><%= "Aucun" if !@meal.course? %></em></dd>

  <dt><strong>Fromage :</strong></dt>
  <% if @meal.cheese %>
    <dd>Oui</dd>
  <% else %>
    <dd>Non</dd>
  <% end %>

  <dt><strong>Salade :</strong></dt>
  <% if @meal.salad %>
    <dd>Oui</dd>
  <% else %>
    <dd>Non</dd>
  <% end %>
  
  <dt><strong>Dessert :</strong></dt>
  <dd><%= @meal.dessert %><em><%= "Aucun" if !@meal.dessert? %></em></dd>
  
  <dt><strong>Notes :</strong></dt>
  <dd><%= @meal.notes %></dd>

</dl>

<div class="form-actions">
  <%= link_to "Retour",
              meals_path, :class => 'btn'  %>
  <%= link_to "Modifier",
              edit_meal_path(@meal), :class => 'btn' %>
  <%= link_to "Supprimer",
              meal_path(@meal),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Êtes vous sûr ?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/search/search.html.erb
<div class="page-header">
	<h1>Les repas avec "<%= params['query'] %>"</h1>
	<h3><%= @meals.count %> résultats de recherche</h3>
</div>
<table class="table table-striped table-hover" id="meals_table">
	<thead>
	    <tr>
	    	<th>Date</th>
	      	<th>Invités</th>
	      	<th>Apéritif</th>
	      	<th>Entrée</th>
	      	<th>Plat</th>
	      	<th>Autre</th>
	      	<th>Dessert</th>
	    </tr>
  	</thead>
  	<tbody>
    	<% @meals.each do |meal| %>
	      	<tr>
	        	<td data-link="<%= meal_path(meal) %>" class="clickable"><%= l(meal.meal_date, :format => "%d/%m/%Y") if meal.meal_date %> 
	          	<% if meal.diner != nil %>
	            <% if meal.diner %>
	              Diner
	            <% else %>
	              Déjeuner
	            <% end %>
	          	<% end %>
	        	</td>
		        <td data-link="<%= meal_path(meal) %>" class="clickable"><%= meal.guest.name if meal.guest %></td>
		        <td data-link="<%= meal_path(meal) %>" class="clickable"><%= meal.aperitif %></td>
		        <td data-link="<%= meal_path(meal) %>" class="clickable"><%= meal.starter %></td>
		        <td data-link="<%= meal_path(meal) %>" class="clickable"><%= meal.course %></td>
		        <td data-link="<%= meal_path(meal) %>" class="clickable"><%= "Fromage" if meal.cheese %><%= " et " if meal.cheese && meal.salad %><%= "Salade" if meal.salad %></td>
		        <td data-link="<%= meal_path(meal) %>" class="clickable"><%= meal.dessert %></td>
	      	</tr>
    	<% end %>
  	</tbody>	
</table>